# Application
spring.application.name=order-service
server.port=8082

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# IMPORTANT:
# Datasource is provided via Docker environment variables:
# SPRING_DATASOURCE_URL
# SPRING_DATASOURCE_USERNAME
# SPRING_DATASOURCE_PASSWORD
# SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT

spring.main.lazy-initialization=false

# Logging
logging.level.org.springframework.web=INFO
logging.level.org.springframework.boot.autoconfigure=INFO
logging.level.com.swiftshop.order=DEBUG

# Stripe
stripe.secretKey=${STRIPE_SECRET_KEY}
stripe.webhookSecret=${STRIPE_WEBHOOK_SECRET}

# Frontend URLs
app.frontendUrl=${FRONTEND_URL:http://localhost:3000}
